//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace videogamescr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AYUDA_CLIENTES
    {
        public int ID_AYUDA { get; set; }
        public string TITULO_ASUNTO { get; set; }
        public string MENSAJE { get; set; }
        public int ID_CLIENTE { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
