//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace videogamescr.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gamestorecrEntities : DbContext
    {
        public gamestorecrEntities()
            : base("name=gamestorecrEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AYUDA_CLIENTES> AYUDA_CLIENTES { get; set; }
        public virtual DbSet<CATALOGO_ACCESORIOS> CATALOGO_ACCESORIOS { get; set; }
        public virtual DbSet<CATALOGO_CONSOLAS> CATALOGO_CONSOLAS { get; set; }
        public virtual DbSet<CATALOGO_JUEGOS> CATALOGO_JUEGOS { get; set; }
        public virtual DbSet<CLIENTES> CLIENTES { get; set; }
        public virtual DbSet<EMPLEADOS> EMPLEADOS { get; set; }
        public virtual DbSet<FACTURAS> FACTURAS { get; set; }
        public virtual DbSet<NOSOTROS> NOSOTROS { get; set; }
        public virtual DbSet<NOTICIAS> NOTICIAS { get; set; }
        public virtual DbSet<PRODUCTOS> PRODUCTOS { get; set; }
        public virtual DbSet<VENTAS> VENTAS { get; set; }
    }
}
