//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace videogamescr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NOSOTROS
    {
        public int ID_NOSOTROS { get; set; }
        public string DESCRIPCION { get; set; }
        public int ID_EMPLEADO { get; set; }
    
        public virtual EMPLEADOS EMPLEADOS { get; set; }
    }
}
