//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace videogamescr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VENTAS()
        {
            this.FACTURAS = new HashSet<FACTURAS>();
        }
    
        public int ID_VENTA { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal MONTO { get; set; }
        public string DESCRIPCION { get; set; }
        public int ID_CLIENTE { get; set; }
        public int ID_PRODUCTO { get; set; }
        public int ID_EMPLEADO { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual EMPLEADOS EMPLEADOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FACTURAS> FACTURAS { get; set; }
        public virtual PRODUCTOS PRODUCTOS { get; set; }
    }
}
